name: News

on:
  schedule:
    - cron: '0 12 * * *' # runs at 12:00 UTC everyday

  workflow_dispatch:
    inputs:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install Google
          pip install datetime
          pip install gtts
          pip install moviepy
          pip install os
          pip install googleapiclient.http
          pip install pickle
          pip install google_auth_oauthlib.flow
          pip install googleapiclient.discovery
          pip install google.auth.transport.requests
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: main.py
          
      - name: commit files
        run: |
          git config --local user.email "rishabhpao2012@gmail.com"
          git config --local user.name "rraj1572"
          git clone https://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@github.com/rraj1572/News
          cd News/
          cd code_samples
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: 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
          branch: main
